const sampleData = [
  {
    url: 'https://www.fanfiction.net/s/14200590/1/Lift-Not-the-Painted-Veil',
    title: 'Lift Not the Painted Veil',
    author: 'Whimsy FF',
    summary:
      'Harry Potter follows Sirius Black through the veil during the fight at the Department of Mysteries. Harry wakes up at midnight on his 11th birthday, moments before Hagrid knocks down the door to the shack. Meanwhile, Sirius breaks out of prison two years early. Time Travel. Powerful Harry. New update every other Sunday.',
    fandoms: 'Harry Potter',
    characters: ['Harry Potter', 'Sirius Black'],
    genres: ['Adventure', 'Mystery'],
    wordCount: 57917,
    review: "best fanfiction I've ever read. Highly recommend to anyone.",
    recommended: true,
    ratingCharacters: 3,
    completed: false,
    ratingPlot: 3,
    ratingGrammar: 3,
    chapterCount: 10,
    notes: ['great start', 'love this next chapter', 'chapter 3 is a banger'],
    status: 'UP_TO_DATE',
    tags: ['time travel'],
    updated: '18 Jun 23',
    published: '19 Feb 23'
  },
  {
    url: 'https://www.fanfiction.net/s/13631456/1/Orochimama',
    title: 'Orochimama',
    author: 'Orochimama',
    summary:
      'Alternate Title: The Snake Goes Ara Ara. By cruel trick of the fates, intervention of stupid gods, or just the apathy of an uncaring universe I find myself awakening as Orochimaru just after he had possessed a woman for his new host. Now I need to find a way to turn this hoard of sycophants and psychos into a force of positive change before I go insane.',
    fandoms: 'Naruto',
    characters: [],
    genres: ['Humor', 'Drama'],
    wordCount: 153459,
    review: 'quite possibly the funniest fanfic ever',
    recommended: true,
    ratingCharacters: 3,
    completed: false,
    ratingPlot: 2,
    ratingGrammar: 2,
    chapterCount: 43,
    notes: ['love the beginning', 'hahaha', 'so funny'],
    status: 'UP_TO_DATE',
    tags: ['self insert'],
    updated: '11 Dec 22',
    published: '1 Jul 20'
  },
    {
    url: 'https://www.fanfiction.net/s/8501689/1/The-Havoc-side-of-the-Force',
    title: 'The Havoc side of the Force',
    author: 'Tsu Doh Nimh',
    summary:
      "I have a singularly impressive talent for messing up the plans of very powerful people - both good and evil. Somehow, I'm always just in the right place at exactly the wrong time. What can I say? It's a gift.",
    fandoms: 'Star Wars & Harry Potter',
    characters: ['Harry Potter'],
    genres: ['Fantasy', 'Mystery'],
    wordCount: 207600,
    review: 'quite possibly the funniest fanfic ever',
    recommended: true,
    ratingCharacters: 3,
    completed: false,
    ratingPlot: 2,
    ratingGrammar: 2,
    chapterCount: 24,
    notes: ['love the beginning', 'hahaha', 'so funny'],
    status: 'UP_TO_DATE',
    tags: ['crossover'],
    updated: '24 Aug 19',
    published: '6 Sep 12'
  },
];

export default sampleData;